### ISSUE TITLE
Default is_multi_region_trail to true

### ISSUE THREAD

**Issue by 0xdabbad00** [threatstack/tf_example_aws_cloudtrail#1]
You should default is_multi_region_trail  at https://github.com/threatstack/tf_example_aws_cloudtrail/blob/master/main.tf#L46 to `true`.

**Comment by tmclaugh** [comment]
I defaulted to false because I wasn't sure how most people setup CloudTrail when they're multi-region.  Do people just create a single CloudTrail or do they do one per region they use?  If one per region they use, then designate one as multi-region to collect for the regions they don't use?  That seems like duplicate work.  Another question I had is whether people use multiple CloudTrails.

I set it to true in the consumer Terraform configuration like below.

https://github.com/threatstack/terraform-example-aws-cloudtrail/blob/master/example-dev.tfvars#L20

I think it's fine to be opinionated on this subject.  But I'm not sure the right answer because I'm not sure what a typical use case is.  At a minimum the variable should be highlighted with an explanation of what to set.  Perhaps I leave no default value to force someone to think about the setting?

**Comment by tmclaugh** [comment]
Your thoughts on this?

**Comment by tmclaugh** [comment]
Unscientific but a start at collecting data.  https://twitter.com/tmclaughbos/status/847817052614270976

**Comment by 0xdabbad00** [comment]
Best practice is to have at least one Cloudtrail flow turned on for all regions.  I saw your post https://blog.threatstack.com/incorporating-aws-security-best-practices-into-terraform-design and you mentioned it should be turned on for all regions, but I think a lot of people might miss that, so it'd be better to do the "right" thing as the default for them, and if they want to get fancy with their setup, they can change it.

I personally have only a single multi-region cloudtrail bucket for our environment  What is the reasoning for not doing that?  Cloudtrail is only capable of logging every 15 minutes, so performance isn't a concern.  It's easy enough to filter through the events for alerting or other needs and it's only adding maybe a few pennies in monthly cost.

**Comment by tmclaugh** [comment]
Thanks for the input!  I've defaulted to `true` and added to the README.
